namePrefix: staging-
commonLabels:
  variant: staging
  org: acmeCorporation
commonAnnotations:
  note: Hello, I am staging!
bases:
- ../../base/helloWorld-2
patchesStrategicMerge:
- map.yaml
- deployment.yaml
