namePrefix: production-
commonLabels:
  variant: production
  org: acmeCorporation
commonAnnotations:
  note: Hello, I am production!
bases:
- ../../base/helloWorld-2
patchesStrategicMerge:
- deployment.yaml
